version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1992
      POSTGRES_DB: servicemanagment
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: yourusername
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    ports:
      - "27017:27017"
  auth_service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  service_management_service:
    build:
      context: ./ServiceManagementService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_started
      mongodb:
        condition: service_started

  user_management_service:
    build:
      context: ./UserManagementService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      rabbitmq:
        condition: service_started
      mongodb:
        condition: service_started
      auth_service:
        condition: service_started
