---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: Jwt__Key
          value: "RTGHAKHJS&SUSHSJJSKJSKSLLLALLLJNHG98542152HDJKDLSDLÇSDKKDD58742JKDJHDJKDKDLLDLLDD6KDJKDJJDD"
        - name: Jwt__Issuer
          value: "AuthService"
        - name: Jwt__Audience
          value: "UserManagementService"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
      - name: user-management-service
        image: user-management-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
        - name: Jwt__Key
          value: "RTGHAKHJS&SUSHSJJSKJSKSLLLALLLJNHG98542152HDJKDLSDLÇSDKKDD58742JKDJHDJKDKDLLDLLDD6KDJKDJJDD"
        - name: Jwt__Issuer
          value: "AuthService"
        - name: Jwt__Audience
          value: "UserManagementService"
        - name: MongoDbSettings__ConnectionString
          value: "mongodb://mongodb:27017"
        - name: MongoDbSettings__DatabaseName
          value: "UserManagementDB"
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-management-service
  template:
    metadata:
      labels:
        app: service-management-service
    spec:
      containers:
      - name: service-management-service
        image: service-management-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5002"
        - name: Jwt__Key
          value: "RTGHAKHJS&SUSHSJJSKJSKSLLLALLLJNHG98542152HDJKDLSDLÇSDKKDD58742JKDJHDJKDKDLLDLLDD6KDJKDJJDD"
        - name: Jwt__Issuer
          value: "AuthService"
        - name: Jwt__Audience
          value: "ServiceManagementService"
        - name: MongoDbSettings__ConnectionString
          value: "mongodb://mongodb:27017"
        - name: MongoDbSettings__DatabaseName
          value: "ServiceManagementDB"
        - name: PostgresConnection
          value: "Host=postgres;Database=servicemanagment;Username=postgres;Password=1992"
---
apiVersion: v1
kind: Service
metadata:
  name: service-management-service
spec:
  type: NodePort
  selector:
    app: service-management-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
    nodePort: 30002
