name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar QEMU (para compatibilidade multi-plataforma)
        uses: docker/setup-qemu-action@v3

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir e enviar AuthService
        uses: docker/build-push-action@v5
        with:
          context: ./AuthService
          file: ./AuthService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

      - name: Construir e enviar UserManagementService
        uses: docker/build-push-action@v5
        with:
          context: ./UserManagementService
          file: ./UserManagementService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-management-service:latest

      - name: Construir e enviar ServiceManagementService
        uses: docker/build-push-action@v5
        with:
          context: ./ServiceManagementService
          file: ./ServiceManagementService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/service-management-service:latest
