name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Executa o workflow quando houver um push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .  # Use o contexto correto para o repositório atual
        file: ./MicroservicesFixit/AuthService/Dockerfile
        push: true
        tags: adeltosilva/auth-service:latest
