name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Executa o workflow quando houver um push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify directory structure
      run: |
        echo "Verifying directory structure..."
        ls -R

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./  # Diretório raiz do repositório
        file: ./AuthService/Dockerfile  # Caminho para o Dockerfile
        push: true
        tags: adeltosilva/auth-service:latest
